
name: Java CD with Maven

on:
  push:
    branches: [ master ]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET: "preston-ewdevops-s3"
  ARTIFACT_NAME: "hello-world.jar"
  AWS_EB_APP_NAME: "devops-cicd-gaction-java-spring"
  AWS_EB_APP_VERSION: "${BUILD_ID}"
  AWS_EB_ENVIRONMENT: "devops-cicd-gaction-java-spring-dev "
  SONAR_IP: "52.23.236.52"
  SONAR_TOKEN: "sqp_6e393ce32b1d8ccbcbeabfe2af993978d8413f38"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Publish artifacts to S3 Bucket
      run: |
        aws configure set region us-east-1
        aws s3 cp ./target/**.jar s3://$AWS_S3_BUCKET/$ARTIFACT_NAME
    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version --application-name $AWS_EB_APP_NAME --version-label $AWS_EB_APP_VERSION --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key=$ARTIFACT_NAME
        aws elasticbeanstalk update-environment --application-name $AWS_EB_APP_NAME --environment-name $AWS_EB_ENVIRONMENT --version-label $AWS_EB_APP_VERSION